---

- name: Ensure download directory exists
  file: path={{ influxdb_download_dir }} state=directory mode=0755
  tags: [influxdb, dirs]

# We get errors on some Python versions because of SNI used at
# https://dl.influxdata.com.  So instead of using get_url we'll just
# shell out to curl.
- name: Download release
  # get_url: url="{{ influxdb_release_url }}" dest="{{ influxdb_download_dir }}/{{ influxdb_release_basename }}"
  command: "curl {{ influxdb_release_url }} -o {{influxdb_release_basename}}"
  args:
    chdir: "{{influxdb_download_dir}}"
    creates: "{{influxdb_download_dir}}/{{influxdb_release_basename}}"
  register: influxdb_download
  tags: [influxdb, download]

- name: Install release
  apt: deb="{{ influxdb_download_dir }}/{{ influxdb_release_basename }}" state=installed
  when: influxdb_download.changed
  tags: [influxdb, install]

- name: Ensure user-owned directories exist
  file: path={{ item }} state=directory owner={{ influxdb_user }} group={{ influxdb_group }} mode=0755
  tags: [influxdb, dirs]
  with_items:
    - "{{ influxdb_home_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_log_dir  }}"

- name: Update configuration file
  template: src=influxdb.conf.j2 dest={{ influxdb_conf_dir }}/influxdb.conf owner=root group=root mode=0644
  notify:
    - restart influxdb
  tags: [influxdb, config]

- name: Ensure service state is configured
  service: name=influxdb state="{{ influxdb_state }}" enabled="{{ influxdb_enabled }}"
  tags: [influxdb, service]
