---

- name: Ensure download directory exists
  file: path={{ influxdb_download_dir }} state=directory mode=0755
  tags:
    - influxdb

# We get errors on some Python versions because of SNI used at
# https://dl.influxdata.com.  So instead of using get_url we'll just
# shell out to curl.
- name: Download release
  # get_url: url="{{ influxdb_release_url }}" dest="{{ influxdb_download_dir }}/{{ influxdb_release_basename }}"
  command: "curl {{ influxdb_release_url }} -o {{influxdb_release_basename}}"
  args:
    chdir: "{{influxdb_download_dir}}"
    creates: "{{influxdb_download_dir}}/{{influxdb_release_basename}}"
  register: influxdb_download
  tags:
    - influxdb

- name: Install release
  apt: deb="{{ influxdb_download_dir }}/{{ influxdb_release_basename }}" state=installed
  when: influxdb_download.changed
  tags:
    - influxdb

- name: Ensure data directory exists
  file: path={{ influxdb_data_dir }} state=directory owner={{ influxdb_user }} group={{ influxdb_group }} mode=0755
  tags:
    - influxdb

- name: Ensure log directory exists
  file: path={{ influxdb_log_dir }} state=directory owner={{ influxdb_user }} group={{ influxdb_group }} mode=0755
  tags:
    - influxdb

- name: Update configuration file
  template: src=influxdb.conf.j2 dest={{ influxdb_conf_dir }}/influxdb.conf owner=root group=root mode=0644
  notify:
    - restart influxdb
  tags:
    - influxdb
